### PR TITLE
fix env init don't create namespace

### LINKED ISSUE #82: [BUG] env:init doesn't create namespace
```
✗ rudr env:init env-hello --namespace env-hello
Create env succeed, current env is env-hello

✗ rudr env env-hello
NAME     	NAMESPACE
env-hello	env-hello%           

✗ kubectl get ns | grep env-hello
```

### PR DESCRIPTION
**Pull request by wonderflow**
fixes #82

### CODE REVIEW

File: pkg/cmd/env.go [hunk 1]
```diff
@@ -166,6 +170,10 @@ func CreateOrUpdateEnv(ctx context.Context, envArgs *types.EnvMeta, args []strin
 	if err != nil {
 		return err
 	}
+	if err := c.Create(ctx, &corev1.Namespace{ObjectMeta: metav1.ObjectMeta{Name: envArgs.Namespace}}); err != nil && !apierrors.IsAlreadyExists(err) {
```
Comment (zzxwill) [inline pkg/cmd/env.go:173]: Checking whether the namespace exists before creating is the other option, which one is better?

Comment (wonderflow) [reply pkg/cmd/env.go:173]: Haha, I think one rpc request win
